services:
  # Notes App Frontend ( Nuxt.js )
  # ----------------------------------------------------------------------------------------------------
  # ...

  # Notes App Database ( MongoDB )
  # ----------------------------------------------------------------------------------------------------
  notes_app_db:
    image: mongo
    container_name: notes_app_db
    ports:
      - "3700:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - notes_app_db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - venomous_app_network

  # MongoDB Express
  # ----------------------------------------------------------------------------------------------------
  notes_app_mongo_express:
    image: mongo-express
    container_name: notes_app_mongo_express
    ports:
      - "3780:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: notes_app_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
    depends_on:
      - notes_app_db
    networks:
      - venomous_app_network

  # Notes App Redis
  # ----------------------------------------------------------------------------------------------------
  notes_app_redis:
    image: redis:latest
    container_name: notes_app_redis
    ports:
      - "3800:6379"
    volumes:
      - notes_app_redis_data:/data
    networks:
      - venomous_app_network

networks:
  venomous_app_network:
    driver: bridge

volumes:
  notes_app_db:
  notes_app_redis_data:
